export default [
    {
        img: `${process.env.PUBLIC_URL}/Momo.jpg`,
        type: "Momo",
        cuisine: "Chicken Steam Momo",
        price: 8.99,
        ingredients:"chopped vegetables or ground meat, chilies, and cilantro.",
        id: 1

    },
    {
        img: `${process.env.PUBLIC_URL}/Thukpa.jpg`,
        type: "Noodles",
        cuisine: "Thukpa",
        price: 1.4,
        ingredients:"noodle soup made with meat or vegetables, noodles, and spices.",
        id: 2

    },
    {
        img: `${process.env.PUBLIC_URL}/Samai.jpg`,
        type: "Traditional",
        cuisine: "Samai",
        price: 7.25,
        ingredients:"buckwheat, millet, or maize flour, gundruk, spiced meat.",
        id: 3
    },
    {
        img: `${process.env.PUBLIC_URL}/Thakali.jpg`,
        type: "ThakaliSet",
        cuisine: "Thakali Khana",
        price: 7,
        ingredients:"rice, lentil soup, gundruk, spiced meat, achar, and vegetables.",
        id: 4
    },
    {
        img: `${process.env.PUBLIC_URL}/Sekuwa.jpg`,
        type: "Starters",
        cuisine: "Sekuwa",
        price: 5,
        ingredients:"skewered grilled meat with cumin, coriander, turmeric, and chili.",
        id: 5
    },
    {
        img: `${process.env.PUBLIC_URL}/dhedo-Food.jpeg`,
        type: "Traditional",
        cuisine: "Dhedo",
        price: 15,
        ingredients:"buckwheat, millet, or maize flour, served with gundruk , achar",
        id: 6
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Momo",
        cuisine: "Chicken Kothey Momo",
        price: 8.99,
        ingredients:"",
        id: 7,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Drinks",
        cuisine: "Tea",
        price: 0.99,
        ingredients:"",
        id: 8,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Drinks",
        cuisine: "Mint Lemonade",
        price: 3.99,
        ingredients:"",
        id: 9,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Drinks",
        cuisine: "Ice Tea",
        price: 1.99,
        ingredients:"",
        id: 10,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Drinks",
        cuisine: "Mango Lassi",
        price: 3.99,
        ingredients:"",
        id: 11,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Drinks",
        cuisine: "Can Soda",
        price: 1.99,
        ingredients:"",
        id: 12,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Drinks",
        cuisine: "Butter Tea",
        price: 2.99,
        ingredients:"",
        id: 13,
    },

    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Drinks",
        cuisine: "Milk Tea",
        price: 1.99,
        ingredients:"",
        id: 14,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Traditional",
        cuisine: "Pulao Small Tray",
        price: 40.00,
        ingredients:"",
        id: 15,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Traditional",
        cuisine: "Goat Curry Big Tray",
        price: 220.00,
        ingredients:"",
        id: 16,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Traditional",
        cuisine: "Rajma Small tray",
        price: 40.00,
        ingredients:"",
        id: 17,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Starters",
        cuisine: "Shadeko Chicken",
        price: 8.99,
        ingredients:"Boiled chicken mixed with nepali spices with a hint of tanginess",
        id: 18,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Starters",
        cuisine: "CHATPATE",
        price: 6.99,
        ingredients:"Nepali street food made with puffed rice and wai wai tossed in raw spices(tangy, spicy)",
        id: 19,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Starters",
        cuisine: "Aloo Jeera",
        price: 6.99,
        ingredients:"Boiled potatoes sauteed with cumin seeds and served with beaten rice",
        id: 20,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Starters",
        cuisine: "Shadeko Bhatmas",
        price: 6.99,
        ingredients:"Roasted soyabeans mixed with raw onions, green chillies, tomatoes with a hint of tanginess",
        id: 21,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Starters",
        cuisine: "Chicken Aloo Jimbu",
        price: 10.99,
        ingredients:"Boneless chicken, potatoes fried and sauteed with himalayan herb served with beaten rice",
        id: 22,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Starters",
        cuisine: "Piro Alu",
        price: 6.99,
        ingredients:"Boiled potatoes sauteed with dry hot chilli and Nepali spices served with beaten rice",
        id: 23,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Starters",
        cuisine: "Tauko Fry",
        price: 10.99,
        ingredients:"Stir fried goat head meat served with beaten rice",
        id: 24,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Starters",
        cuisine: "Goat Sekuwa",
        price: 11.99,
        ingredients:"marinated goat chunks grilled to perfection, served with puffed rice and Nepali pickle",
        id: 25,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Starters",
        cuisine: "Chicken Choila",
        price: 8.99,
        ingredients:"boneless chicken grilled and marinated with raw Himalayan spices served with beaten rice",
        id: 26,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Starters",
        cuisine: "RajKhani",
        price: 10.99,
        ingredients:"stir fried goat testicles served with beaten rice",
        id: 27,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Starters",
        cuisine: "Bhutan",
        price: 10.99,
        ingredients:"stir fried(goat intestine, liver, heart, kidney) with Nepali spices",
        id: 28,
    },
    {
        img: `${process.env.PUBLIC_URL}/`,
        type: "Starters",
        cuisine: "Duck Choila",
        price: 8.99,
        ingredients:"Bone-in duck fried and marinated with raw spices (spicy)",
        id: 29,
    },
    

]